function KoConstructor() {
  this.data = {
    header: 'Munich - city of Lederhosen, OnPage.org & SEOktoberfest',
    p1: "Germany has become more and more popular with households on holiday staying in self catering apartments and vacation villas. Sunshine fans flock to Germany in the months of the summer and several select to stay in a luxurious villa with a swimming pool. In the wintertime, it is incredibly popular with winter sport enthusiasts, vacation rentals can be found to rent in all the main skiing resorts from skiing chalets to self catering apartments. There are a large number of towns in Germany that may be of interest to tourists. The capital city of Berlin provides an extensive selection of things for tourists to indulge in.",
    p2: "While there you can stay in among the many luxury self catering flats or vacation villas in the capital. This city is well known for the historic past of Germany. The Berlin wall is the most renowned historic site in Berlin. Many visitors rent a luxury villa or vacation apartment and use this as a foundation to learn more about the local culture and night life. The lively and energetic night life in Germany attracts a large number of tourists every year. The local guides aid to teach us about the city and country. It is located in the central state Hesse of Germany.",
    p3: "This can be famous for two things, the international airfield and its futuristic skyline. The city is popular for the large number of museums it's. The district has the highest number of museums within the city. Tourists visiting the nation around June may encounter the renowned Kieler Woche festival. This week long festival takes place at the harbor of Kiel. You can see the oldest to the latest ships of Germany in this parade. Military ships, sailing boats and old tall ships may also be seen by millions. There are various holiday houses and self catering flats to rent nearby.",
    p4: "Rhine in Flames is another popular festival in Germany. The festival takes place once per month in several towns. The ship parade also characterizes <a href='/knockout-external/test/'>the firework festival</a>. Munich is the 3rd largest city within the nation and capital of Bavaria. This beer and wine festival takes place in October in Munich each year. Whenever people think of this festival they think of large glasses of wine, mouth watering sausages, ladies wearing dirndls and men wearing Lederhosen. Millions of individuals visit Munich throughout the festival."
  }
}

ko.applyBindings(new KoConstructor(), document.getElementById('app-root'));